require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'PodPublishReact' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
  use_react_native!
  
  pod 'Alamofire'

end
